In [1]:
import pandas as pd

In [3]:
a = pd.read_csv('./a.csv')
a

                날짜                         댓글  조회수  좋아요  싫어요
0       2022-05-03                  개미들 조련하는법   26    1    0
1       2022-05-03                        6만원   38    1    0
2       2022-05-03             카카오는 끝물입니다 사실상   72    2    2
3       2022-05-03                    안티 살발하다   34    2    0
4       2022-05-03            이런 호로개미지옥탕을 만드신   58    3    1
...            ...                        ...  ...  ...  ...
299995  2017-10-18  어차피 또 폭등할텐데 떨필요있나 기회주면...  795   15    3
299996  2017-10-18  오늘 물렸다고 생각하는 사람들은 도대체 ...  961    3    2
299997  2017-10-18                        내일도  618    5    1
299998  2017-10-18              아마존 per는 300?  745    4    1
299999  2017-10-18                  퍼가 180???  563    2    3

[300000 rows x 5 columns]

In [7]:
b = pd.read_csv('./b.csv')
del b['링크']
del b['제목']
b

              날짜    정보제공                                                 기사
0     2022-04-29   머니투데이  \n\t\t\t [[2022 키플랫폼]이기원 서울대 푸드테크학과장]이기원 서울대학교...
1     2022-04-29  이코노미스트  \n소상공인 지원 프로그램 ‘톡스토어X판판대로 과정’ 오픈     톡스토어X판판대로...
2     2022-04-29  파이낸셜뉴스  \n카카오톡 쇼핑하기, 중소기업유통센터와 협업소상공인 판매자 위한 교육지원 프로그램...
3     2022-04-28    한국경제  \n삼성전자, 연봉인상률 9% 논의노사협의회, 임금 협상 진행 상황 공지카카오 15...
4     2022-04-28  이코노미스트  \n환경 문제 해결하기 위한 '액티브 그린 이니셔티브' 공개카카오 탄소 지수로 이행...
...          ...     ...                                                ...
5571  2021-05-03  파이낸셜뉴스  \n‘톡스토어 판매자 양성과정’ 참가자 1200명제주도 등 전국 6개 창조경제혁신센...
5572  2021-05-03    서울경제  \n\t\t\t [서울경제] 카카오와 카카오커머스는 전국 6개 창조경제혁신센터와 손...
5573  2021-05-01    매일경제  \n카카오모빌리티에서 운영하는 카카오T바이크 [매경DB] 바야흐로 공유자전거 전성시...
5574  2021-04-30   머니투데이  \n\t\t\t [머니투데이 구단비 기자] [[오늘의 포인트]]/사진제공=네이버오는...
5575  2021-04-30  파이낸셜뉴스  \n방문 세차-전기차 충전에 이어 ‘방문 정비' 서비스‘내비 운행 리포트’ 리뉴얼,...

[5576 rows x 3 columns]

In [8]:
b = pd.read_csv('./b.csv')
del b['링크']
b

,날짜,제목,정보제공,기사
0,2022-04-29,"""미래 푸드테크, 삼성·SK·네이버·카카오도 진출할 것""",머니투데이,\n\t\t\t [[2022 키플랫폼]이기원 서울대 푸드테크학과장]이기원 서울대학교...
1,2022-04-29,‘상생 행보’ 카카오…중기유통센터 손잡고 소상공인 지원,이코노미스트,\n소상공인 지원 프로그램 ‘톡스토어X판판대로 과정’ 오픈 톡스토어X판판대로...
2,2022-04-29,소상공인 파트너와 성장하는 ‘톡스토어’..카카오,파이낸셜뉴스,"\n카카오톡 쇼핑하기, 중소기업유통센터와 협업소상공인 판매자 위한 교육지원 프로그램..."
3,2022-04-28,"""카카오·네이버보다도 못하다고?""…삼성맨들 '부글부글'",한국경제,"\n삼성전자, 연봉인상률 9% 논의노사협의회, 임금 협상 진행 상황 공지카카오 15..."
4,2022-04-28,2040년까지 탄소 순 배출량 '0' 만든다…카카오 '넷 제로' 원칙 ...,이코노미스트,\n환경 문제 해결하기 위한 '액티브 그린 이니셔티브' 공개카카오 탄소 지수로 이행...
...,...,...,...,...
5571,2021-05-03,"카카오-카카오커머스, ‘톡스토어 판매자’ 키운다",파이낸셜뉴스,\n‘톡스토어 판매자 양성과정’ 참가자 1200명제주도 등 전국 6개 창조경제혁신센...
5572,2021-05-03,"카카오·카카오커머스, '톡스토어' 판매자 양성 과정 진행",서울경제,\n\t\t\t [서울경제] 카카오와 카카오커머스는 전국 6개 창조경제혁신센터와 손...
5573,2021-05-01,KT와 카카오의 공유자전거 힘겨루기…T바이크에 타조 맞불,매일경제,\n카카오모빌리티에서 운영하는 카카오T바이크 [매경DB] 바야흐로 공유자전거 전성시...
5574,2021-04-30,"네이버 오른다는데…공매도 타깃된 카카오 ""나 떨고있니?""",머니투데이,\n\t\t\t [머니투데이 구단비 기자] [[오늘의 포인트]]/사진제공=네이버오는...
5575,2021-04-30,"카카오내비, ‘방문 정비’ 시작 “주행분석까지 한다”",파이낸셜뉴스,"\n방문 세차-전기차 충전에 이어 ‘방문 정비' 서비스‘내비 운행 리포트’ 리뉴얼,..."