In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

import warnings
warnings.filterwarnings('ignore')

In [10]:
code = '035420' # 네이버 종목코드
page = 10000 # 크롤 희망 페이지 (페이지당 20개 댓글)

date_list = [] # 날짜
comment_list = [] # 댓글
view_list = [] # 조회수
good_list = [] # 좋아요
bad_list = [] # 싫어요

for i in range(5100,page+1):
    url = f'https://finance.naver.com/item/board.naver?code={code}&page={i}'
    headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50'}
    res = requests.get(url, headers = headers)
    bs = BeautifulSoup(res.text, 'html.parser')
    
    for j in range(20):
        try:
            root = bs.find('div',{'class':'section inner_sub'}).find_all('tr',{'onmouseover':'mouseOver(this)'})[j].text.split('\n')
            
            date_list.append(root[1].split()[0].replace('.','-'))
            if len(root) == 14: # 답글
                comment_list.append('답글:'+root[4])
                view_list.append(root[10])
                good_list.append(root[11])
                bad_list.append(root[12])          
            elif len(root) == 13: # 기본
                comment_list.append(root[3])
                view_list.append(root[9])
                good_list.append(root[10])
                bad_list.append(root[11])
            else: # 에러
                comment_list.append('error')
                view_list.append(0)
                good_list.append(0)
                bad_list.append(0)   
                
        except:
            date_list.append('error')
            comment_list.append('error')
            view_list.append(0)
            good_list.append(0)
            bad_list.append(0)   
            
    
    if i % 500 == 0:
        print(f'{i}페이지 크롤링 완료')

5500페이지 크롤링 완료
6000페이지 크롤링 완료
6500페이지 크롤링 완료
7000페이지 크롤링 완료
7500페이지 크롤링 완료
8000페이지 크롤링 완료
8500페이지 크롤링 완료
9000페이지 크롤링 완료
9500페이지 크롤링 완료
10000페이지 크롤링 완료

In [15]:
df = pd.DataFrame()
df['날짜'] = date_list
df['댓글'] = comment_list
df['조회수'] = view_list
df['좋아요'] = good_list
df['싫어요'] = bad_list
df

               날짜                    댓글  조회수 좋아요 싫어요
0      2017-06-09              일단은 ~~~~  252   2   2
1      2017-06-09              얜왜오르는거죠?  669   1   1
2      2017-06-09  역쉬 친구하난 똑똑해 네이버 삼성만큼  408   0   0
3      2017-06-09         금요일 빨간불이면 뭐다?  413   2   2
4      2017-06-09                신고가 돌파  302   1   1
...           ...                   ...  ...  ..  ..
98015       error                 error    0   0   0
98016       error                 error    0   0   0
98017       error                 error    0   0   0
98018       error                 error    0   0   0
98019       error                 error    0   0   0

[98020 rows x 5 columns]

In [13]:
df[df['댓글'] != 'error']

               날짜                         댓글   조회수 좋아요 싫어요
0      2017-06-09                   일단은 ~~~~   252   2   2
1      2017-06-09                   얜왜오르는거죠?   669   1   1
2      2017-06-09       역쉬 친구하난 똑똑해 네이버 삼성만큼   408   0   0
3      2017-06-09              금요일 빨간불이면 뭐다?   413   2   2
4      2017-06-09                     신고가 돌파   302   1   1
...           ...                        ...   ...  ..  ..
98009  2017-06-08                        조만간   413   2   3
98010  2017-06-08                        네이버   545   1   4
98011  2017-06-07  코스피 대형주..외국인 기관 쌍끌이 매수...   666   0   0
98012  2017-06-07                        네이버   688   0   4
98013  2017-06-07              ■ 평단 300.000원  1017   1   0

[68614 rows x 5 columns]

In [ ]:
df.to_csv("./src/네이버종토방댓글_네이버_10000.csv", index=False)